// Generates src/core/static/fonts.rn.ts — RN-side thunk map for fonts.
//
// Each entry is a `() => require(...)` thunk so Metro bundles each asset
// as a separate module. The thunks are only invoked at runtime via
// Font.loadAsync, so a consumer that only navigates to pages 1–100 only
// ships those 100 TTF files in the final binary.
//
// Mirrors src/core/static/fonts.ts (web) but reads from the RN-only
// TTF directories and the hafs-unicode assets (which are already .otf /
// .ttf and don't need a parallel directory).

import { readdirSync, statSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import path from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = join(__dirname, "..");
const FONTS_SRC = join(PROJECT_ROOT, "src/data/fonts");
const SHARED_SRC = join(PROJECT_ROOT, "src/data/shared");
const STATIC_OUT = join(PROJECT_ROOT, "src/core/static");

// hafs-{v2,v4}-ttf → per-page thunks, keyed by the *layout name* (hafs-v2 / hafs-v4)
// so consumers can index `staticFonts[layout][page]` with the standard
// MushafLayout enum. The directory name is an implementation detail.
// hafs-unicode     → 2 keys: digitalkhatt (otf), ayatquran (ttf, special-cased)
const PAGE_LAYOUTS: Array<[layoutKey: string, dirName: string]> = [
  ["hafs-v2", "hafs-v2-ttf"],
  ["hafs-v4", "hafs-v4-ttf"],
];

function pageNumFromName(filename: string): number | null {
  const m = filename.match(/^p(\d+)\.ttf$/i);
  if (!m) return null;
  return Number(m[1]);
}

function buildPagesBlock(
  layoutKey: string,
  dirName: string,
): string {
  const dir = join(FONTS_SRC, dirName);
  if (!statSync(dir, { throwIfNoEntry: false })) {
    throw new Error(
      `RN font directory missing: ${dir}. Run scripts/download-fonts.ts or scripts/convert-woff2-to-ttf.ts first.`,
    );
  }
  const entries = readdirSync(dir)
    .map((name) => ({ name, page: pageNumFromName(name) }))
    .filter((e): e is { name: string; page: number } => e.page !== null)
    .sort((a, b) => a.page - b.page);

  if (entries.length === 0) {
    throw new Error(`No p*.ttf files found in ${dir}`);
  }

  const inner = entries
    .map(
      ({ page, name }) =>
        `    ${page}: () => require("../../data/fonts/${dirName}/${name}"),`,
    )
    .join("\n");

  return `  "${layoutKey}": {\n${inner}\n  },`;
}

function buildUnicodeBlock(): string {
  // Walk src/data/fonts/hafs-unicode/ and emit the 2 keys we care about.
  // Mirrors the lowercase + special-case logic from scripts/generate-static-fonts.ts.
  const dir = join(FONTS_SRC, "hafs-unicode");
  if (!statSync(dir, { throwIfNoEntry: false })) {
    throw new Error(`hafs-unicode font directory missing: ${dir}`);
  }

  const wanted: Record<string, string> = {};
  for (const name of readdirSync(dir)) {
    const lower = name.replace(/\.(otf|ttf)$/i, "").toLowerCase();
    let key: string;
    if (lower === "ayatquran2-pvkgm") key = "ayatquran";
    else if (lower === "digitalkhatt") key = "digitalkhatt";
    else continue; // skip anything else
    wanted[key] = name;
  }

  if (!wanted.digitalkhatt || !wanted.ayatquran) {
    throw new Error(
      `hafs-unicode must contain digitalkhatt.* and AyatQuran2-PVKGm.ttf; got ${JSON.stringify(wanted)}`,
    );
  }

  return (
    `  "hafs-unicode": {\n` +
    `    digitalkhatt: () => require("../../data/fonts/hafs-unicode/${wanted.digitalkhatt}"),\n` +
    `    ayatquran: () => require("../../data/fonts/hafs-unicode/${wanted.ayatquran}"),\n` +
    `  },`
  );
}

function buildSurahnameBlock(): string {
  const path = join(SHARED_SRC, "surah-name-v4.ttf");
  if (!statSync(path, { throwIfNoEntry: false })) {
    throw new Error(
      `surah-name-v4.ttf not found at ${path}. Run scripts/download-surah-name.ts first.`,
    );
  }
  return `  surahname: () => require("../../data/shared/surah-name-v4.ttf"),`;
}

function generateFontsRn(): string {
  const blocks: string[] = [];
  for (const [layoutKey, dirName] of PAGE_LAYOUTS) {
    blocks.push(buildPagesBlock(layoutKey, dirName));
  }
  blocks.push(buildUnicodeBlock());
  blocks.push(buildSurahnameBlock());

  return (
    `// AUTO-GENERATED by scripts/generate-static-fonts-rn.ts — do not edit.\n` +
    `//\n` +
    `// Each entry is a lazy () => require(...) thunk so Metro bundles each\n` +
    `// asset as a separate module. Thunks are only invoked at runtime via\n` +
    `// Font.loadAsync, so a consumer that only navigates to a subset of\n` +
    `// pages only ships those TTF files in the final binary.\n` +
    `\n` +
    `export const staticFonts = {\n` +
    blocks.join("\n") +
    `\n} as const;\n`
  );
}

const content = generateFontsRn();
mkdirSync(STATIC_OUT, { recursive: true });
const outputPath = join(STATIC_OUT, "fonts.rn.ts");
writeFileSync(outputPath, content, "utf-8");
console.log(`Generated ${outputPath}`);