import { existsSync, readdirSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PROJECT_ROOT = join(__dirname, "..");
const DATA_SRC = join(PROJECT_ROOT, "src/data");
const STATIC_OUT = join(PROJECT_ROOT, "src/core/static");

const HELPER_FUNCTIONS = `
export function getPagesUrl(layout: string): string {
  const url = staticData.pages?.[layout as keyof typeof staticData.pages];
  if (!url) throw new Error(\`Pages not found: \${layout}\`);
  return url;
}

export function getMetadataUrl(type: "surahs" | "juz"): string {
  const url = staticData.metadata?.[type];
  if (!url) throw new Error(\`Metadata not found: \${type}\`);
  return url;
}

export function getSurahNameFontUrl(): string {
  const url = staticData.shared?.surahname;
  if (!url) throw new Error(\`Surah name font not found\`);
  return url;
}

export function getSurahFrameUrl(): string {
  const url = staticData.assets?.surahFrame;
  if (!url) throw new Error(\`Surah frame SVG not found\`);
  return url;
}
`;

/** Generates data.web.ts – uses new URL(…, import.meta.url).href for Vite/tsup */
function generateWebData(): string {
  let output = `export const staticData = {\n`;

  if (existsSync(join(DATA_SRC, "pages"))) {
    output += `  pages: {\n`;
    const pagesDir = readdirSync(join(DATA_SRC, "pages"));
    for (const layout of pagesDir) {
      const pagesPath = join(DATA_SRC, "pages", layout, "pages.json");
      if (existsSync(pagesPath)) {
        output += `    "${layout}": new URL(\n`;
        output += `      "../../data/pages/${layout}/pages.json",\n`;
        output += `      import.meta.url,\n`;
        output += `    ).href,\n`;
      }
    }
    output += `  },\n`;
  }

  if (existsSync(join(DATA_SRC, "metadata"))) {
    output += `  metadata: {\n`;
    const metadataDir = readdirSync(join(DATA_SRC, "metadata"));
    for (const file of metadataDir) {
      if (existsSync(join(DATA_SRC, "metadata", file)) && file.endsWith(".json")) {
        const name = file.replace(".json", "");
        output += `    ${name}: new URL("../../data/metadata/${file}", import.meta.url).href,\n`;
      }
    }
    output += `  },\n`;
  }

  if (existsSync(join(DATA_SRC, "shared"))) {
    output += `  shared: {\n`;
    const sharedDir = readdirSync(join(DATA_SRC, "shared"));
    for (const file of sharedDir) {
      if (existsSync(join(DATA_SRC, "shared", file))) {
        output += `    surahname: new URL("../../data/shared/${file}", import.meta.url).href,\n`;
      }
    }
    output += `  },\n`;
  }

  if (existsSync(join(DATA_SRC, "assets"))) {
    const canonicalFrame = "surah-frame-wikipedia.svg";
    const canonicalPath = join(DATA_SRC, "assets", canonicalFrame);
    if (existsSync(canonicalPath)) {
      output += `  assets: {\n`;
      output += `    surahFrame: new URL("../../data/assets/${canonicalFrame}", import.meta.url).href,\n`;
      output += `  },\n`;
    }
  }


  output += `} as const;\n\n`;
  output += `export type StaticData = typeof staticData;\n`;
  output += HELPER_FUNCTIONS;

  return output;
}

/**
 * Generates data.rn.ts – uses static require() thunks for per-page JSON splits.
 * Expects src/data/pages/{layout}/p{N}.json to exist (run split-pages.ts first).
 */
function generateRnData(): string {
  let output = `// Auto-generated by scripts/generate-static-data.ts\n`;
  output += `// Each page thunk is a lazy require() so Metro bundles them separately.\n\n`;

  const layouts = ["hafs-v2", "hafs-v4", "hafs-unicode"];
  const PAGE_COUNT = 604;

  output += `export const pageDataThunks: Record<string, Record<number, () => unknown>> = {\n`;
  for (const layout of layouts) {
    const layoutPagesDir = join(DATA_SRC, "pages", layout);
    // Only emit if per-page files actually exist
    const firstPageFile = join(layoutPagesDir, "p1.json");
    if (!existsSync(firstPageFile)) {
      output += `  // "${layout}": per-page files not found — run yarn generate:pages:split first\n`;
      continue;
    }
    output += `  "${layout}": {\n`;
    for (let p = 1; p <= PAGE_COUNT; p++) {
      output += `    ${p}: () => require("../../data/pages/${layout}/p${p}.json"),\n`;
    }
    output += `  },\n`;
  }
  output += `};\n\n`;

  // Surah name font as a Metro-resolved require (TTF)
  output += `export const surahNameFontAsset = `;
  const sharedDir = join(DATA_SRC, "shared");
  if (existsSync(sharedDir)) {
    const sharedFiles = readdirSync(sharedDir);
    const ttf = sharedFiles.find((f) => /\.(ttf|otf)$/i.test(f));
    if (ttf) {
      output += `require("../../data/shared/${ttf}");\n\n`;
    } else {
      output += `null; // No TTF/OTF found in shared/ — run generate:fonts first\n\n`;
    }
  } else {
    output += `null;\n\n`;
  }

  output += `export function getPageDataThunk(\n`;
  output += `  layout: string,\n`;
  output += `  page: number,\n`;
  output += `): () => unknown {\n`;
  output += `  const thunk = pageDataThunks[layout]?.[page];\n`;
  output += `  if (!thunk) throw new Error(\`Page thunk not found: \${layout}/\${page}\`);\n`;
  output += `  return thunk;\n`;
  output += `}\n`;

  return output;
}

mkdirSync(STATIC_OUT, { recursive: true });

// Web variant (keeps backward-compat name data.ts as well for tsup)
const webContent = generateWebData();
writeFileSync(join(STATIC_OUT, "data.web.ts"), webContent, "utf-8");
writeFileSync(join(STATIC_OUT, "data.ts"), webContent, "utf-8");
console.log(`Generated ${STATIC_OUT}/data.web.ts (and data.ts alias)`);

// React Native variant
const rnContent = generateRnData();
writeFileSync(join(STATIC_OUT, "data.rn.ts"), rnContent, "utf-8");
console.log(`Generated ${STATIC_OUT}/data.rn.ts`);
