// Generates src/core/static/data.rn.ts — RN-side thunk map for page data.
//
// Each layout has a single `_all` thunk that loads the bundled pages.json
// (produced by scripts/fetch-pages.ts). Mirrors the existing web behavior
// in src/core/data-loader.ts where the full pages.json is fetched once
// and indexed by page number.
//
// Per-page JSON splitting (a real split-pages.ts) is intentionally NOT
// done in Phase 3 — see the plan's risk register: this is a future
// optimization, not a 0.7.0 requirement.

import { writeFileSync, mkdirSync, statSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import path from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = join(__dirname, "..");
const PAGES_SRC = join(PROJECT_ROOT, "src/data/pages");
const STATIC_OUT = join(PROJECT_ROOT, "src/core/static");

const LAYOUTS = ["hafs-v2", "hafs-v4", "hafs-unicode"] as const;

function generateDataRn(): string {
  const blocks: string[] = [];
  for (const layout of LAYOUTS) {
    const jsonPath = join(PAGES_SRC, layout, "pages.json");
    if (!statSync(jsonPath, { throwIfNoEntry: false })) {
      throw new Error(
        `pages.json not found at ${jsonPath}. Run scripts/fetch-pages.ts first.`,
      );
    }
    blocks.push(
      `  "${layout}": { _all: () => require("../../data/pages/${layout}/pages.json") },`,
    );
  }

  return (
    `// AUTO-GENERATED by scripts/generate-static-data-rn.ts — do not edit.\n` +
    `//\n` +
    `// One _all thunk per mushaf, mirroring the web's loadPages(layout)\n` +
    `// behavior (fetches the full pages.json once and indexes in memory).\n` +
    `// See src/core/data-loader.rn.ts for the consumer.\n` +
    `\n` +
    `export const staticData = {\n` +
    blocks.join("\n") +
    `\n} as const;\n`
  );
}

const content = generateDataRn();
mkdirSync(STATIC_OUT, { recursive: true });
const outputPath = join(STATIC_OUT, "data.rn.ts");
writeFileSync(outputPath, content, "utf-8");
console.log(`Generated ${outputPath}`);