// AUTO-GENERATED by scripts/generate-static-data-rn.ts — do not edit.
//
// One _all thunk per mushaf, mirroring the web's loadPages(layout)
// behavior (fetches the full pages.json once and indexes in memory).
// See src/core/data-loader.rn.ts for the consumer.

export const staticData = {
  "hafs-v2": { _all: () => require("../../data/pages/hafs-v2/pages.json") },
  "hafs-v4": { _all: () => require("../../data/pages/hafs-v4/pages.json") },
  "hafs-unicode": { _all: () => require("../../data/pages/hafs-unicode/pages.json") },
} as const;
