// AUTO-GENERATED by scripts/generate-static-fonts-rn.ts — do not edit.
//
// Per-layout font loaders for RN. Page-specific TTF assets are loaded
// via a runtime-built require() dispatched through a Function
// constructor so Metro cannot statically walk the entire 604-page
// font graph into the initial bundle. Only the TTF for the page
// actually rendered enters the dependency graph. Shared fonts
// (DigitalKhatt, AyatQuran, SurahName) stay as static one-shot thunks
// because they're always loaded together at app startup.

export const staticFonts = {
  "hafs-v2": {
    // Dynamic per-page loader. The require is called inside a Function
    // constructor so Metro's static analyzer cannot follow it — only
    // the TTF for the page actually rendered enters the dependency graph.
    forPage: (page: number): unknown => {
      const num = String(page).padStart(3, "0");
      const dynamicRequire: (p: string) => unknown = new Function(
        "p",
        "return require(p);",
      ) as (p: string) => unknown;
      return dynamicRequire(
        "../../data/fonts/hafs-v2-ttf/p" + num + ".ttf",
      );
    },
  },
  "hafs-v4": {
    // Dynamic per-page loader. The require is called inside a Function
    // constructor so Metro's static analyzer cannot follow it — only
    // the TTF for the page actually rendered enters the dependency graph.
    forPage: (page: number): unknown => {
      const num = String(page).padStart(3, "0");
      const dynamicRequire: (p: string) => unknown = new Function(
        "p",
        "return require(p);",
      ) as (p: string) => unknown;
      return dynamicRequire(
        "../../data/fonts/hafs-v4-ttf/p" + num + ".ttf",
      );
    },
  },
  "hafs-unicode": {
    digitalkhatt: () => require("../../data/fonts/hafs-unicode/digitalkhatt.otf"),
    ayatquran: () => require("../../data/fonts/hafs-unicode/AyatQuran2-PVKGm.ttf"),
  },
  surahname: () => require("../../data/shared/surah-name-v4.ttf"),
} as const;
